### ISSUE TITLE
Rico project link

### ISSUE THREAD

**Issue by maxdevjs** [rajatsharma/rajatsharma.github.io#2]
Hello,

not really sure if I got the right source, but shouldn't https://github.com/rajatsharma/rajatsharma.github.io/blob/d34f16715a79196ebe069152cef88799fb9e8b46/src/Links.js#L67

actually be:

```js
link="rico"
```

?

**Comment by rajatsharma** [comment]
Yes, I renamed the project and forgot to change here. 😅

**Comment by rajatsharma** [comment]
Fixed. Thanks. 😊
